name: Test
on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Terraform action to perform'
        required: true
        default: 'apply'
        type: choice
        options:
          - apply
          - destroy
      region:
        description: 'Provide region'
        required: true
        default: 'us-east-1'

      ami_id:
        description: 'Enter ami id'
        required: true

      instance_type:
        description: 'Provide instance type'
        required: true
        default: 't2.micro'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Git Clone
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: "1.12.2"

    - name: Create tfvars file
      run: |
        cat <<EOF > terraform.tfvars
        ami_id = "${{ inputs.ami_id }}"
        instance_type = "${{ inputs.instance_type }}"
        region = "${{ inputs.region }}"
        EOF

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4.3.1
      with:
        aws-access-key-id: "${{ secrets.AWS_ACCESS_KEY_ID }}"
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2

    - name: Init
      run: terraform init

    - name: Terraform Action
      run: |
        if [[ "${{ inputs.action }}" == "apply" ]]; then
          terraform apply -auto-approve
        else
          terraform destroy -auto-approve
        fi
